_base_: '../global_configs.yml'

batch_size: 2
iters: 10000

train_dataset:
  type: LungCoronavirus
  dataset_root: lung_coronavirus/lung_coronavirus_phase0
  result_dir: lung_coronavirus/lung_coronavirus_phase1
  transforms:
    - type: RandomFlip3D
  mode: train
  num_classes: 3

val_dataset:
  type: LungCoronavirus
  dataset_root: lung_coronavirus/lung_coronavirus_phase0
  result_dir: lung_coronavirus/lung_coronavirus_phase1
  transforms:
    - type: RandomFlip3D
  mode: val
  num_classes: 3


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0003
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: DiceLoss
  coef: [1]
