_base_: '../_base_/global_configs.yml'

batch_size: 4
iters: 10000

train_dataset:
  type: LungCoronavirus
  dataset_root: lung_coronavirus/lung_coronavirus_phase0
  result_dir: lung_coronavirus/lung_coronavirus_phase1
  transforms:
    - type: RandomFlip3D
  mode: train
  num_classes: 3

val_dataset:
  type: LungCoronavirus
  dataset_root: lung_coronavirus/lung_coronavirus_phase0
  result_dir: lung_coronavirus/lung_coronavirus_phase1
  transforms:
    - type: RandomFlip3D
  mode: val
  num_classes: 3
  post_transforms:
    - type: BinaryMaskConnectCompoent

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0003
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: [0.2, 0.4, 0.4]
        - type: DiceLoss
      coef: [0.5, 0.5]
  coef: [1]
